### ISSUE TITLE
View Filtered Results From Update/Apply Filter Menu

### ISSUE THREAD

**Issue by TalynLangford** [gdharper/Pathfinder_Feat_Explorer#7]
Clunky interaction -- shouldn't have to step back to the main menu to view the filtered list of Feats. Option should exist to both take you back & view the list, or perhaps to just view the list from that menu.

**Comment by TalynLangford** [comment]
After using a bit more, I'm not so sure about this. One thing that does seem strange to me is asking the user to apply changes to the feat database after they've selected and input them. Is this to let the user check the changes before they're applied? It feels like an unnecessary step right now.

**Comment by gdharper** [comment]
That was my initial thought, but I agree it does feel lie too much menu-hopping. I'll move everything that has to do with filtering to a single sub-menu and see if that feels more natural

**Comment by gdharper** [comment]
@TalynLangford try the newest HEAD commit, see what you think.
I'm going to close this issue unless you hate the new UX
